version: '3.8'
services:
  # to run development 
  dev:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.dev
    container_name: V2-Fxdx-Dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules

  # to run production 
  prod:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.prod
    container_name: V2-Fxdx-Prod
    ports: 
      - '3011:3000'

